/* ------------------ DATA FOR BUSINESS MODEL ------------------ */
/* ------------------ CLEAR TABLES ------------------ */
-- Has to be in this order because of dependencies
DELETE FROM PROCESSEDBY;
DELETE FROM SALE;
DELETE FROM SALEDESCRIPTION;
DELETE FROM ITEMSBOUGHT;
DELETE FROM ITEM;
DELETE FROM PURCHASES;
DELETE FROM EMPLOYEE;
DELETE FROM CUSTOMER;

/* ------------------ POPULATE TABLES ------------------ */
-- Populate Employees

--INSERT INTO EMPLOYEE VALUES 
--  ('0001','Alice','Adams',NULL,'100 LANCASTER AVE','01JAN2000',NULL,16.75,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0002','Bob','Brown',NULL,'101 LANCASTER AVE','01JAN2000',NULL,18.20,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0003','Catherine','Campbell',NULL,'102 LANCASTER AVE','01JAN2000',NULL,19.50,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0004','David','Diaz',NULL,'103 LANCASTER AVE','01JAN2000',NULL,15.80,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0005','Emily','Edwards',NULL,'104 LANCASTER AVE','01JAN2000',NULL,17.25,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0006','Frank','Fisher',NULL,'105 LANCASTER AVE','01JAN2000',NULL,18.90,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0007','Grace','Gonzalez',NULL,'106 LANCASTER AVE','01JAN2000',NULL,16.40,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0008','Henry','Harris',NULL,'107 LANCASTER AVE','01JAN2000',NULL,19.00,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0009','Isabel','Irwin',NULL,'108 LANCASTER AVE','01JAN2000',NULL,17.60,'0');
INSERT INTO EMPLOYEE VALUES 
  ('0010','Jack','Johnson',NULL,'109 LANCASTER AVE','01JAN2000',NULL,15.30,'0');
  
-- Populate Customers
INSERT INTO CUSTOMER VALUES 
  ('0001','Eva','Anderson',NULL,'200 LANCASTER AVE','0');
INSERT INTO CUSTOMER VALUES 
  ('0002','Brian','Smith',NULL,'201 LANCASTER AVE','0');
INSERT INTO CUSTOMER VALUES 
  ('0003','Sophia','Johnson',NULL,'202 LANCASTER AVE','0');
INSERT INTO CUSTOMER VALUES 
  ('0004','Oliver','Williams',NULL,'203 LANCASTER AVE','0');
INSERT INTO CUSTOMER VALUES 
  ('0005','Chloe','Brown',NULL,'204 LANCASTER AVE','0');
INSERT INTO CUSTOMER VALUES 
  ('0006','Liam','Jones',NULL,'205 LANCASTER AVE','150');
INSERT INTO CUSTOMER VALUES 
  ('0007','Charlotte','Martinez',NULL,'206 LANCASTER AVE','0');
INSERT INTO CUSTOMER VALUES 
  ('0008','Mason','Taylor',NULL,'207 LANCASTER AVE','0');
INSERT INTO CUSTOMER VALUES 
  ('0009','Amelia','Harris',NULL,'208 LANCASTER AVE','0');
INSERT INTO CUSTOMER VALUES 
  ('0010','Lucas','Thompson',NULL,'209 LANCASTER AVE','0');
  
-- Populate Items
INSERT INTO ITEM VALUES 
  ('0001','Apple','5.00');
INSERT INTO ITEM VALUES 
  ('0002','Banana','3.50');
INSERT INTO ITEM VALUES 
  ('0003','Orange','4.25');
INSERT INTO ITEM VALUES 
  ('0004','Grapes','6.75');
INSERT INTO ITEM VALUES 
  ('0005','Strawberry','8.00');
INSERT INTO ITEM VALUES 
  ('0006','Watermelon','10.50');
INSERT INTO ITEM VALUES 
  ('0007','Pineapple','7.25');
INSERT INTO ITEM VALUES 
  ('0008','Mango','9.75');
INSERT INTO ITEM VALUES 
  ('0009','Kiwi','2.75');
INSERT INTO ITEM VALUES 
  ('0010','Peach','6.00');

/* ------------------ DISPLAY TABLES ------------------ */
--SELECT * FROM EMPLOYEE;
--SELECT * FROM CUSTOMER;
--SELECT * FROM ITEM;
--SELECT * FROM ITEMSBOUGHT;
--SELECT * FROM PROCESSEDBY;
--SELECT * FROM PURCHASES;
--SELECT * FROM SALE;
--SELECT * FROM SALEDESCRIPTION;
